version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - SQL_USER=root
      - SQL_PASSWORD=123456
      - SQL_DB=testdb
    ports:
      - 3306:3306

  shortener:
    container_name: shortener
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SQL_IP=mysql-db
      - SQL_USER=root
      - SQL_PASSWORD=123456
      - SQL_DB=testdb
      - HOST=mysql-db
    depends_on:
      - mysql-db
