version: "3.8"

services:
  mysql-db:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    container_name: mysql-db
    environment:
      - SQL_USER=root
      - SQL_PASSWORD=123456
      - SQL_DB=testdb
    ports:
      - 3306:3306
    volumes:
      - mysql-db-data:/var/lib/mysql/data

  shortener:
    image: akmalhakimteo/akmal-url-shortener:version1.0
    container_name: shortener
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SQL_IP=mysql-db
      - SQL_USER=root
      - SQL_PASSWORD=123456
      - SQL_DB=testdb
      - HOST=mysql-db
    depends_on:
      - mysql-db
