version: '3.8'

services:
  backend:
    build: ./backend
    ports:
     - "8080:8080"
    container_name: shortener-backend
    environtment: 
      ENV PORT 8080
      ENV SQL_IP localhost
      ENV SQL_USER root
      ENV SQL_PASSWORD 123456
      ENV SQL_DB testdb
      ENV HOST mysql-db

