version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          


jobs:
  test:
    working_directory: ~/repo/backend
    docker:
      - image: cimg/node:16.12.0
    steps:
      - checkout:
         path: ~/repo
      - run:
          name: Install dependencies
          command: npm install
      - run: 
          name: run tests backend
          command: npm run test
      
  build:
    working_directory: ~/repo/backend
    docker:
      - image: cimg/node:16.12.0
    steps:
      - checkout:
         path: ~/repo
      - run:
          name: rebuild frontend statics
          command: npm run build
      - run:
          name: Build docker image
          command: docker build -t akmalhakimteo/akmal-url-shortener:version1.0
    
    

        
      
