version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      - build and push:
          requires:
            - test
          


jobs:
  test:
    working_directory: ~/repo/backend
    docker:
      - image: cimg/node:16.12.0
    steps:
      - checkout:
         path: ~/repo
      - run:
          name: Install dependencies
          command: npm install
      - run: 
          name: run tests backend
          command: npm run test
      
  build and push:
    working_directory: ~/repo/backend
    docker:
      - image: cimg/node:16.12.0
    steps:
      - checkout:
         path: ~/repo
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: rebuild frontend statics
          command: npm run build
      - run:
          name: Build docker image
          command: docker build -t akmal-url-shortener . 
      - run:
          name: Tagging docker image
          command: docker tag akmal-url-shortener akmalhakimteo/akmal-url-shortener:version1.0.$CIRCLE_BUILD_NUM
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push akmalhakimteo/akmal-url-shortener:version1.0.$CIRCLE_BUILD_NUM

    

        
      
