version: 2.1

workflows:
  test-deploy:
  jobs:
    - test

jobs:
  test:
    working_directory: ~/repo/backend
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: node --version
